export const GET_JOIN_EVENT_REQUEST = "GET_JOIN_EVENT_REQUEST";
export const GET_JOIN_EVENT_SUCCESS = "GET_JOIN_EVENT_SUCCESS";
export const GET_JOIN_EVENT_FAILURE = "GET_JOIN_EVENT_FAILURE";

export const ADD_JOIN_EVENT_SUCCESS = "ADD_JOIN_EVENT_SUCCESS";

export const GET_CURRENT_USER_JOIN_EVENT_SUCCESS =
  "GET_CURRENT_USER_JOIN_EVENT_SUCCESS";
